### ISSUE TITLE
AWX: Badge Designs

### ISSUE THREAD

**Issue by Ompragash** [ansible-community/ansible-badges#6]
## Vote _a_ or _b_ to choose either of these designs!

a)
![awx_contributor](https://user-images.githubusercontent.com/21008429/190134881-34b4059f-5597-4ae7-9c28-bbda5e854551.png) ![awx_community](https://user-images.githubusercontent.com/21008429/190134899-2d4f89a4-026e-407a-8688-a10456abfe50.png)
---------------

b)
![contributor_awx](https://user-images.githubusercontent.com/21008429/190135703-168db611-6f9a-4512-82d6-cae00046b90b.png) ![community_awx](https://user-images.githubusercontent.com/21008429/190135732-50371d3f-d3f6-4a41-b324-836bb81d4e97.png)

**Comment by john-westcott-iv** [comment]
I think my vote is B since they are more inline with the existing badges. If other components also create badges this would lead to something unified amongst the projects.

**Comment by jainnikhil30** [comment]
My Vote is for B !

**Comment by rooftopcellist** [comment]
My vote is also B

**Comment by rebeccahhh** [comment]
Also voting B between these 2 options

**Comment by gundalow** [comment]
It's great to see more Ansible Projects look at using Badges. 
I also vote B, for style and it matching existing.

**Comment by cybette** [comment]
Both look amazing!

Voting for B for consistency

**Comment by Ompragash** [comment]
Awesome! then I'll create a badge issuer with the B badges and will sync up with @john-westcott-iv for issuing the same:)

Thanks @cybette @gundalow @rebeccahhh @rooftopcellist @jainnikhil30 @john-westcott-i!

**Comment by cybette** [comment]
@Ompragash I just noticed that the "CONTRIBUTOR" word is not vertically centered like "COMMUNITY" is. Can you edit it, or provide the source file so we can make the edit? I'm trying to order stuff for AnsibleFest so we need it quite urgently. Thanks!

**Comment by cybette** [comment]
Ok it's not so urgent anymore, stickermule is able to make the adjustment directly to the order. However it will still be nice for us to have the source files and/or updated graphics, at your convenience! Thanks again @Ompragash :heart:

**Comment by Ompragash** [comment]
My bad yeah I notice that mistake too. Will correct it and upload the source file to this repo:) thanks @cybette❤️✨
